// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpfbvvqkznadjelajrwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwZmJ2dnFrem5hZGplbGFqcndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzU1MjIsImV4cCI6MjA2MTM1MTUyMn0.dUB7v_ojPunXGtawRu_KrLGs7otWpHrq3J2C-iKjF8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);